package com.erp.dao;

import com.erp.bean.Customer;
import com.erp.bean.CustomerExample;
import com.erp.dto.CustomerCityDto;
import com.erp.dto.CustomerProvinceDto;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Wed May 01 19:59:42 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Wed May 01 19:59:42 CST 2024
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Wed May 01 19:59:42 CST 2024
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Wed May 01 19:59:42 CST 2024
     */
    List<Customer> selectByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Wed May 01 19:59:42 CST 2024
     */
    Customer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Wed May 01 19:59:42 CST 2024
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Wed May 01 19:59:42 CST 2024
     */
    int updateByPrimaryKey(Customer record);

    List<Customer> selectByComIdAndUserName(@Param("comId") Integer comId,@Param("name") String name);

    List<CustomerCityDto> getCustomerCityData(Integer comId);
    List<CustomerProvinceDto> getCustomerProvinceData(Integer comId);
}