package com.erp.dao;

import com.erp.bean.OrderItems;
import com.erp.bean.OrderItemsExample;
import java.util.List;

public interface OrderItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbg.generated Fri May 03 20:23:42 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbg.generated Fri May 03 20:23:42 CST 2024
     */
    int insert(OrderItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbg.generated Fri May 03 20:23:42 CST 2024
     */
    int insertSelective(OrderItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbg.generated Fri May 03 20:23:42 CST 2024
     */
    List<OrderItems> selectByExample(OrderItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbg.generated Fri May 03 20:23:42 CST 2024
     */
    OrderItems selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbg.generated Fri May 03 20:23:42 CST 2024
     */
    int updateByPrimaryKeySelective(OrderItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbg.generated Fri May 03 20:23:42 CST 2024
     */
    int updateByPrimaryKey(OrderItems record);

    /**
     * @description 根据订单id删除订单商品明细
     * @author xielulin
     * @date 2024/4/26
     * @param orderId
     * @return int
     */
    int deleteByOrderId(Integer orderId);
}