server:
  port: 8081
mybatis:
  mapper-locations: classpath:mapping/*.xml

spring:
  datasource:
    name: erp
    url: jdbc:mysql://111.230.100.213:3306/erp?characterEncoding=utf8&useUnicode=true&verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: Mysqltx123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 111.230.100.213
    password: redistx123
    timeout: 30s
    connect-timeout: 30s
    jedis:
      pool:
        max-active: 200
        max-wait: 30s
        max-idle: 100
        min-idle: 8
#短信
message:
  sdk:
    app:
      id: 1400900640
  template:
    id: 2138114
  sign:
    name: 开单宝网站