spring:
  application:
    name: erp
  profiles:
    active: dev
    include: message
server:
  servlet:
    context-path: /erp

redis:
  jedis:
    pool:
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池的最大数据库连接数
      max-active: 8
      # #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1ms