package com.erp.bean;

public class Business {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.id
     *
     * @mbg.generated Thu Apr 25 11:46:01 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.name
     *
     * @mbg.generated Thu Apr 25 11:46:01 CST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.tel
     *
     * @mbg.generated Thu Apr 25 11:46:01 CST 2024
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.addr
     *
     * @mbg.generated Thu Apr 25 11:46:01 CST 2024
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.province
     *
     * @mbg.generated Thu Apr 25 11:46:01 CST 2024
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.city
     *
     * @mbg.generated Thu Apr 25 11:46:01 CST 2024
     */
    private String city;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.id
     *
     * @return the value of business.id
     *
     * @mbg.generated Thu Apr 25 11:46:01 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.id
     *
     * @param id the value for business.id
     *
     * @mbg.generated Thu Apr 25 11:46:01 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.name
     *
     * @return the value of business.name
     *
     * @mbg.generated Thu Apr 25 11:46:01 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.name
     *
     * @param name the value for business.name
     *
     * @mbg.generated Thu Apr 25 11:46:01 CST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.tel
     *
     * @return the value of business.tel
     *
     * @mbg.generated Thu Apr 25 11:46:01 CST 2024
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.tel
     *
     * @param tel the value for business.tel
     *
     * @mbg.generated Thu Apr 25 11:46:01 CST 2024
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.addr
     *
     * @return the value of business.addr
     *
     * @mbg.generated Thu Apr 25 11:46:01 CST 2024
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.addr
     *
     * @param addr the value for business.addr
     *
     * @mbg.generated Thu Apr 25 11:46:01 CST 2024
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.province
     *
     * @return the value of business.province
     *
     * @mbg.generated Thu Apr 25 11:46:01 CST 2024
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.province
     *
     * @param province the value for business.province
     *
     * @mbg.generated Thu Apr 25 11:46:01 CST 2024
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.city
     *
     * @return the value of business.city
     *
     * @mbg.generated Thu Apr 25 11:46:01 CST 2024
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.city
     *
     * @param city the value for business.city
     *
     * @mbg.generated Thu Apr 25 11:46:01 CST 2024
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }
}