package com.erp.bean;

import java.util.Date;

public class Company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.id
     *
     * @mbg.generated Thu Apr 25 14:12:13 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.com_name
     *
     * @mbg.generated Thu Apr 25 14:12:13 CST 2024
     */
    private String comName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.level
     *
     * @mbg.generated Thu Apr 25 14:12:13 CST 2024
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.is_valid
     *
     * @mbg.generated Thu Apr 25 14:12:13 CST 2024
     */
    private Boolean isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.valid_date
     *
     * @mbg.generated Thu Apr 25 14:12:13 CST 2024
     */
    private Date validDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.id
     *
     * @return the value of company.id
     *
     * @mbg.generated Thu Apr 25 14:12:13 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.id
     *
     * @param id the value for company.id
     *
     * @mbg.generated Thu Apr 25 14:12:13 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.com_name
     *
     * @return the value of company.com_name
     *
     * @mbg.generated Thu Apr 25 14:12:13 CST 2024
     */
    public String getComName() {
        return comName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.com_name
     *
     * @param comName the value for company.com_name
     *
     * @mbg.generated Thu Apr 25 14:12:13 CST 2024
     */
    public void setComName(String comName) {
        this.comName = comName == null ? null : comName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.level
     *
     * @return the value of company.level
     *
     * @mbg.generated Thu Apr 25 14:12:13 CST 2024
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.level
     *
     * @param level the value for company.level
     *
     * @mbg.generated Thu Apr 25 14:12:13 CST 2024
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.is_valid
     *
     * @return the value of company.is_valid
     *
     * @mbg.generated Thu Apr 25 14:12:13 CST 2024
     */
    public Boolean getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.is_valid
     *
     * @param isValid the value for company.is_valid
     *
     * @mbg.generated Thu Apr 25 14:12:13 CST 2024
     */
    public void setIsValid(Boolean isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.valid_date
     *
     * @return the value of company.valid_date
     *
     * @mbg.generated Thu Apr 25 14:12:13 CST 2024
     */
    public Date getValidDate() {
        return validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.valid_date
     *
     * @param validDate the value for company.valid_date
     *
     * @mbg.generated Thu Apr 25 14:12:13 CST 2024
     */
    public void setValidDate(Date validDate) {
        this.validDate = validDate;
    }
}