package com.erp.bean;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.name
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.com_id
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    private Integer comId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.logistics_name
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    private String logisticsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.tel
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.addr
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.province
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.city
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.create_time
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss",timezone = "GMT+08" )
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.user_id
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.is_del
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id
     *
     * @return the value of customer.id
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id
     *
     * @param id the value for customer.id
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.name
     *
     * @return the value of customer.name
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.name
     *
     * @param name the value for customer.name
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.com_id
     *
     * @return the value of customer.com_id
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.com_id
     *
     * @param comId the value for customer.com_id
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.logistics_name
     *
     * @return the value of customer.logistics_name
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    public String getLogisticsName() {
        return logisticsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.logistics_name
     *
     * @param logisticsName the value for customer.logistics_name
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    public void setLogisticsName(String logisticsName) {
        this.logisticsName = logisticsName == null ? null : logisticsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.tel
     *
     * @return the value of customer.tel
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.tel
     *
     * @param tel the value for customer.tel
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.addr
     *
     * @return the value of customer.addr
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.addr
     *
     * @param addr the value for customer.addr
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.province
     *
     * @return the value of customer.province
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.province
     *
     * @param province the value for customer.province
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.city
     *
     * @return the value of customer.city
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.city
     *
     * @param city the value for customer.city
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.create_time
     *
     * @return the value of customer.create_time
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.create_time
     *
     * @param createTime the value for customer.create_time
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.user_id
     *
     * @return the value of customer.user_id
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.user_id
     *
     * @param userId the value for customer.user_id
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.is_del
     *
     * @return the value of customer.is_del
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.is_del
     *
     * @param isDel the value for customer.is_del
     *
     * @mbg.generated Tue May 14 15:49:37 CST 2024
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}