package com.erp.bean;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id
     *
     * @mbg.generated Wed Apr 17 19:56:18 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.name
     *
     * @mbg.generated Wed Apr 17 19:56:18 CST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.com_id
     *
     * @mbg.generated Wed Apr 17 19:56:18 CST 2024
     */
    private Integer comId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.logistics_name
     *
     * @mbg.generated Wed Apr 17 19:56:18 CST 2024
     */
    private String logisticsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.tel
     *
     * @mbg.generated Wed Apr 17 19:56:18 CST 2024
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.addr
     *
     * @mbg.generated Wed Apr 17 19:56:18 CST 2024
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.is_del
     *
     * @mbg.generated Wed Apr 17 19:56:18 CST 2024
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id
     *
     * @return the value of customer.id
     *
     * @mbg.generated Wed Apr 17 19:56:18 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id
     *
     * @param id the value for customer.id
     *
     * @mbg.generated Wed Apr 17 19:56:18 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.name
     *
     * @return the value of customer.name
     *
     * @mbg.generated Wed Apr 17 19:56:18 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.name
     *
     * @param name the value for customer.name
     *
     * @mbg.generated Wed Apr 17 19:56:18 CST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.com_id
     *
     * @return the value of customer.com_id
     *
     * @mbg.generated Wed Apr 17 19:56:18 CST 2024
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.com_id
     *
     * @param comId the value for customer.com_id
     *
     * @mbg.generated Wed Apr 17 19:56:18 CST 2024
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.logistics_name
     *
     * @return the value of customer.logistics_name
     *
     * @mbg.generated Wed Apr 17 19:56:18 CST 2024
     */
    public String getLogisticsName() {
        return logisticsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.logistics_name
     *
     * @param logisticsName the value for customer.logistics_name
     *
     * @mbg.generated Wed Apr 17 19:56:18 CST 2024
     */
    public void setLogisticsName(String logisticsName) {
        this.logisticsName = logisticsName == null ? null : logisticsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.tel
     *
     * @return the value of customer.tel
     *
     * @mbg.generated Wed Apr 17 19:56:18 CST 2024
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.tel
     *
     * @param tel the value for customer.tel
     *
     * @mbg.generated Wed Apr 17 19:56:18 CST 2024
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.addr
     *
     * @return the value of customer.addr
     *
     * @mbg.generated Wed Apr 17 19:56:18 CST 2024
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.addr
     *
     * @param addr the value for customer.addr
     *
     * @mbg.generated Wed Apr 17 19:56:18 CST 2024
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.is_del
     *
     * @return the value of customer.is_del
     *
     * @mbg.generated Wed Apr 17 19:56:18 CST 2024
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.is_del
     *
     * @param isDel the value for customer.is_del
     *
     * @mbg.generated Wed Apr 17 19:56:18 CST 2024
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}