package com.erp.bean;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.tel
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.com_id
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    private Integer comId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_valid
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    private Boolean isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.valid_date
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    private Date validDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.order_tel
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    private String orderTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.level
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    private Integer level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.tel
     *
     * @return the value of user.tel
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.tel
     *
     * @param tel the value for user.tel
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.com_id
     *
     * @return the value of user.com_id
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.com_id
     *
     * @param comId the value for user.com_id
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_valid
     *
     * @return the value of user.is_valid
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    public Boolean getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_valid
     *
     * @param isValid the value for user.is_valid
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    public void setIsValid(Boolean isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.valid_date
     *
     * @return the value of user.valid_date
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    public Date getValidDate() {
        return validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.valid_date
     *
     * @param validDate the value for user.valid_date
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    public void setValidDate(Date validDate) {
        this.validDate = validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.order_tel
     *
     * @return the value of user.order_tel
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    public String getOrderTel() {
        return orderTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.order_tel
     *
     * @param orderTel the value for user.order_tel
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    public void setOrderTel(String orderTel) {
        this.orderTel = orderTel == null ? null : orderTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.level
     *
     * @return the value of user.level
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.level
     *
     * @param level the value for user.level
     *
     * @mbg.generated Tue May 14 12:00:12 CST 2024
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}